### ISSUE TITLE
Add a readme and some screenshots

### ISSUE THREAD

**Issue by Haroenv** [bignerdranch/remotebot#22]
We also have a remote office live feed, and I was wondering if this would be useful for us. How specific to your live feed is this? We use google hangouts, but it's on 24/7

**Comment by nybblr** [comment]
Hi @Haroenv, sorry I missed this! @jeremy-w just added a README with a little background. You can use it as a status for pretty much anything; we use it for company-wide meetings. We made a physical glowing orb to show folks in the office when the feed has trouble, but you can pretty much build anything to be an "indicator".

**Comment by Haroenv** [comment]
Awesome, seems like a nice project!
